### ISSUE TITLE
module :datetime_format_lexer is not available

### ISSUE THREAD

**Issue by danschultzer** [kipcole9/cldr_dates_times#1]
The `:datetime_format_lexer` module is not compiled when installing the library.

Looks like `src` is missing in https://github.com/kipcole9/cldr_dates_times/blob/master/mix.exs#L72

**Comment by kipcole9** [comment]
Apologies for the stupid error and slow response (am traveling  in remote Mongolia and internet isn't everywhere).  Fixed and release v0.1.2 is now on hex.
