### ISSUE TITLE
ex_cldr dependency broken version

### ISSUE THREAD

**Issue by naaano** [kipcole9/cldr_dates_times#7]
ex_cldr is currently at v = 2.2
but in this version is locket at 1.8 which fails to compile. 
Can you update it?

thank you

**Comment by kipcole9** [comment]
@naaano Sorry for the inconvenience.  However `ex_cldr_dates_times` is not yet compatible with `ex_cldr` version 2.x.  This is a major release with breaking architectural changes.  I am working on a new release of `ex_cldr_dates_times` but it won't be completed for at least 2 weeks.

Functionally, `ex_cldr` 1.x is almost the same as the 2.x series.  Therefore I suggest stay with the `1.x` series for now and I'll finish up the next version of `ex_cldr_dates_times` as quickly as possible.
